- dialog.xcodeproj/project.pbxproj
- dialog.xcodeproj/xcuserdata/rea094.xcuserdatad/xcschemes/xcschememanagement.plist
- dialog/Info.plist
- dialog/UI/BannerImageView.swift
- dialog/UI/ButtonView.swift
- dialog/UI/ContentView.swift
- dialog/UI/DialogView.swift
- dialog/UI/DropdownView.swift
- dialog/UI/FullscreenView.swift
- dialog/UI/IconOverlayView.swift
- dialog/UI/MessageContentView.swift
- dialog/appVaribles.swift
- dialog/dialogApp.swift
- dialog/extras/Options.swift
- dialog/extras/Processing.swift
Yeah, two in one. 1.2 was rolled into 1.3 prior to a PR. Is what it is.
1.2 -> added option for specifying a dropdown box that a user can pick from
1.3 -> compiled target to a cli only binary that can be placed in `usr/local/bin`. This may be the only option moving forward, or now I'm releasing the cli version and the app bundle.
> Add Dropdown options and Command Line app.

- dialog/UI/ButtonView.swift
- dialog/UI/FullscreenView.swift
- dialog/UI/IconOverlayView.swift
- dialog/UI/IconView.swift
- dialog/appVaribles.swift
- dialog/dialogApp.swift
- dialog/extras/Processing.swift
Adjusted button text rendering - fixes display issue with default "OK" button in macos 12
Fixed the way icon and icon overlay are rendered. This makes scaling between different views a _lot_ more consistent.
Fixed fullscreen view rendering. Fullscreen now accepts font colours for the title. Also renders overlay icons properly in the proper scale for the display
> Fix fullscreen and some other cleanup

- dialog.xcodeproj/project.pbxproj
- dialog/UI/DialogView.swift
- dialog/UI/IconOverlayView.swift
- dialog/UI/IconView.swift
- dialog/appVaribles.swift
1.4.2 RC2
Tweaked how the icon and overlay icon behave.
If there's no overlay, icon is displayed larger (full scale). If there is an overlay, the icon is scaled down slightly with overlay applied to fill the space that would be otherwise occupied by a single image.
overlay icon can also have a background colour specified when using SF Symbols by adding `bgcolour=` to the image definition.
> Icon tweaking

- dialog/Info.plist
- dialog/UI/DropdownView.swift
- dialog/UI/IconOverlayView.swift
- dialog/UI/MessageContentView.swift
- dialog/UI/TextEntryView.swift
- dialog/appVaribles.swift
- dialog/extras/ProcessCLOptions.swift
- dialog/extras/TrackProgress.swift
- dialog/extras/helpText.swift
- dialog/extras/jamfHelper.swift
- enhancement to options that can be modified by command file:
- added `--listitem` [more details in the wiki](https://github.com/bartreardon/Dialog/wiki/Item-Lists)
- added `iconsize` as one of the supported jamfhelper options
- cleaned up `selectvalues` when using json as an input source. json will look like:
```json
{
"selecttitle" : "Title Here",
"selectvalues" : ["Select 1", "Select 2", "Select 3"],
"selectdefault" : "Select 3"
}
```
- fixed an issue with setting the number of progress increments as a command line argument. Was always defaulting to `100`
> Dialog 1.9.1

- dialog.xcodeproj/xcuserdata/rea094.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
- dialog/Info.plist
- dialog/UI/ButtonView.swift
- dialog/UI/DropdownView.swift
- dialog/UI/MessageContentView.swift
- dialog/UI/TextEntryView.swift
- dialog/appVaribles.swift
- dialog/extras/ProcessCLOptions.swift
- dialog/extras/Processing.swift
- dialog/extras/TrackProgress.swift
This change adds `secure` and `required` as properties on text fields.
- `secure` - The text entry field becores a secure field where the text being typed is not shown (aka a password field)
- `required` - The text field must be populated or swiftDialog will not exit using the OK button. Button 2 (cancel) or button 3 (info) behaviour is not changed
With this comes an expansion to how textfields can be defined either as a command line argument or from json
In addition to the existing method, the command line argument can now take the form `--textfield "<field name>,required,secure` where `required` and `secure` are optional.
the JSON formatting can now be expressed like the following
```json
{
"textfield" : [
{"title" : "Username", "required" : true},
{"title" : "Password", "secure" : …
```
> Secure and required text entry

- dialog.xcodeproj/project.pbxproj
- dialog/Info.plist
- dialog/UI/DropdownView.swift
- dialog/UI/MessageContentView.swift
- dialog/appVaribles.swift
- dialog/extras/ProcessCLOptions.swift
- dialog/extras/Processing.swift
adds multiple dropdown support.
as command line argument add multiple  `--selecttitle`, `--selectvalues` and `--selectdefault`. values, titles and defaults are assigned in the order they are presented
as json:
```json
"selectitems" : [
{"title" : "Select 1", "values" : ["one","two","three"]},
{"title" : "Select 2", "values" : ["red","green","blue"], "default" : "red"},
{"title" : "Select 3", "values" : ["up","down","left","right"]}
]
```
results:
```bash
Select 1 : one
Select 1 index : 0
Select 2 : green
Select 2 index : 1
Select 3 : left
Select 3 index : 2
```
results as json output:
```json
{
"Select 2" : {
"selectedIndex" : 1,
"selectedValue" : "green"
},
"Select 1" : {
"selectedIndex" : 0,
"selectedValue" : "one"
},
"Select 3" : {
"selectedIndex" : 2,
"selectedValue" : "left"
}
}
``` …
> Multi dropdown

- dialog/Info.plist
- dialog/dialogApp.swift
fixed the window activation logic so the window doesn't steal focus when sending updates to it
if `--ontop` or `--blurscreen` options are present then we can assume we do what that behaviour so in those cases we re-activate the window when an update is sent.
> fixed window activation logic

- dialog.xcodeproj/project.pbxproj
- dialog/Info.plist
- dialog/UI/IconOverlayView.swift
- dialog/UI/IconView.swift
- dialog/extras/Processing.swift
on macOS 12, SF Symbols will render using the hierarchical scheme by default with the specified single colour
> Added extra system colours available in macOS 12

- dialog/extras/helpText.swift
`--help` and the [Command Line Options](https://github.com/bartreardon/swiftDialog/wiki/Command-Line-Options) wiki page incorrectly listed `font=<fontname>` rather than `name=<fontname>`
> Correcting  --titlefont parameter in helpText

- dialog/extras/helpText.swift
The default value of --commandFile was incorrectly shown as /var/log/dialog.log. It should instead be /var/tmp/dialog.log.
> Corrected --commandFile default value

- dialog/Functions/System.swift
This should make the isDNDEnabled work for macOS 11+. This does assume that Dialog.app is executed by the currently logged-in user (which is how Dialog.app is meant to be executed).
Thanks for all the hard work with this project @bartreardon!
> Refactor isDNDEnabled function to work for macOS 11+

- dialog.xcodeproj/project.pbxproj
- dialog/Classes/DialogUpdatableContent.swift
- dialog/Functions/Log.swift
- dialog/Functions/Notifications.swift
- dialog/Functions/ProcessCLOptions.swift
- dialog/Functions/System.swift
- dialog/Info.plist
- dialog/Package/pkgroot/usr/local/bin/dialog
- dialog/Structs/AppVariables.swift
- dialog/Structs/ImageProcessing.swift
- dialog/Views/ButtonView.swift
- dialog/dialogApp.swift
- `isDNDEnabled()` refactored to work under macOS 12+ (thanks @ryangball). Future use pending
- updates to `/usr/local/bin/dialog` to handle errors a bit more cleanly and send errors to stderr instead of stdout
- updates to general error and log handling sending error and debug output to stderr
- Add a check of launch time and compare against command file modification date. if the command file is older then existing commands stored within will not be processed
- command file processing is now less dependent on ownership or permissions. As long as the file is readable. Errors in this department provide more detail and output to stderr and should only occur if the file is not readable.
- button1 respects `button1disabled` if centred
- progress text will populate if updated by command file …
> swiftDialog v2.3.2

- dialog/Functions/Strings.swift
- dialog/Structs/HelpText.swift
- dialog/Views/IconView.swift
This change set will allow the user to specify a value of `accent` where macOS standard colour values are accepted, indicating that the colour applied should be the one chosen by the user via `System Settings > Appearance > Accent Colour`.  This affects the following:
- Title colour
- Message colour
- Icon colour (when a Symbol is specified for the icon)
This change set also addresses a discrepancy between the documentation, and the actual handling of multicolour SF Symbols when the colour value `auto` is specified.  Currently, this value does not actually allow the Symbol to be displayed in multicolour mode, as its `.symbolRenderingMode` is set to `.hierarchical`.  This is fixed by adding a `var` to track the usage of `auto`, and a check against that `var` to determine whether …
> Enable User's Preferred Accent Colour & Fix `auto` Symbol Rendering 

- dialog.xcodeproj/project.pbxproj
- dialog/Classes/DialogUpdatableContent.swift
- dialog/Extensions/Colour+Additions.swift
- dialog/Extensions/Font+Additions.swift
- dialog/Extensions/String+Additions.swift
- dialog/Functions/ProcessCLOptions.swift
- dialog/Functions/Strings.swift
- dialog/Functions/System.swift
- dialog/Views/ConstructionKit/ConstructionKitView.swift
- dialog/Views/IconView.swift
- dialog/Views/TextEntryView.swift
- `'brown'` (`Color.brown`)
- `'primary'` (`Color.primary`)
- `'secondary'` (`Color.secondary`)
- `'ultralight'` (`Font.Weight.ultraLight`)
- `'semibold'`  (`Font.Weight.semibold`)
- `'black'`  (`Font.Weight.black`)
- Add `init(argument:)`.
- Relocates `textToFontWeight(_:)` utility function.
- Add `init(argument:)`.
- Relocates `stringToColour(_:)` utility function. 
- Add `var hexValue`.
- Relocates `colourToString(color:)` utility function.
- Add `var sha256Hash`.
- Relocates `hashForString(_:)` utility function.
> Add Missing System Font Weights and Colors; Move Color/String/Font Utilities to Extensions

- dialog/Command Line/HelpText.swift
- dialog/Views/ButtonView.swift
Adds an additional _stack_ style for buttons, which displays the buttons full width in a vertical stack.  A slight amount of padding was added to mimic macOS native dialogs with stacked buttons.
Similar to the _center_ style, the new _stack_ style would also disable `--timer` and `--infobutton`.
> Adds 'stack' style for buttons

- dialog/Command Line/HelpText.swift
I tried to fix typos that are invalid in both UK and US english (to the best of my knowledge). Anything with UK spelling was left alone.
> Fix typos in help text

- dialog.xcodeproj/project.pbxproj
For folks whose Xcode is defaulted to using tabs for indentation (sorry!), this setting forces spaces over tabs explicitly at the top of the project to match how the project is indented
> explicitly use spaces instead of tabs

- dialog/Command Line/ProcessCLOptions.swift
- dialog/dialogApp.swift
Simplifies loginwindow option by fully implying ontop. Fixes focus and window level issues
> Imply ontop when using loginwindow

- dialog.xcodeproj/project.pbxproj
- dialog/App Processing/AppVariables.swift
- dialog/Command Line/CommandLineArguments.swift
- dialog/Command Line/ProcessCLOptions.swift
- dialog/Functions/Notifications.swift
- dialog/Info.plist
- dialog/Views/MessageContentView.swift
- dialog/dialogApp.swift
hotfix release to address some issues in 2.5.3
- notifications causing boilerplate windows popping up
- boilerplate text being used when "" is provided to denote a null value
- overlay icons not showing when using a single --icon and --centreicon is used
> swiftDialog 2.5.4

- dialog.xcodeproj/project.pbxproj
- dialog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- dialog/App Processing/AppVariables.swift
- dialog/Command Line/CommandLineArguments.swift
- dialog/Command Line/ProcessCLOptions.swift
- dialog/Functions/Log.swift
- dialog/Functions/System.swift
- dialog/Info.plist
- dialog/Package/pkgroot/usr/local/bin/dialog
- dialog/Updatable Content/DialogUpdatableContent.swift
- dialog/Views/ButtonView.swift
- dialog/Views/HelpView.swift
- dialog/dialogApp.swift
Fixes:
- #476 Notifications no longer trigger action items from --button1action or --button2action
- #473 Applying the blur effect then turning it off puts a dialog on top even if it is not on top
- #477 timer flag causing dialog to stay open indefinitely
- Added processing to handle if no arguments are used on the command line. This should allow enough time for whatever script is being launced from a notification to launch.
- Fix issue where default string values were not being populated on arguments with optional values
- updated logic for `/usr/local/bin/dialog` to avoid permission issues and warn if the command file is detected as a symlink
Updates:
- #463 customize the label on the Help pane’s close button to any desired text `--helpsheetbuttontext`
> swiftDialog 2.5.5

- dialog/Command Line/CommandLineArguments.swift
- dialog/Command Line/HelpText.swift
- dialog/Functions/Notifications.swift
Ability to set an identifier for a notification, allowing you to easily replace a notification with an updated one. Also the ability to remove a specific notification by identifier or all notifications.
Example:
```
dialog --notification --identifier "update.message" --title "Updates" --message "Please update by tonight."
dialog --notification --identifier "update.message" --title "Updates" --message "Please update within the next hour."
dialog --notification --identifier "update.message" --remove
```
https://github.com/user-attachments/assets/725cd1f4-ef3c-4fad-9bfc-e371d7720835
> Additional options for working with notifications

- dialog/Package/pkgroot/usr/local/bin/dialog
Suppresses the no user error when calling the --version command using the dialog shell script if no user is logged in: /usr/local/bin/dialog --version
id: loginwindow: no such user
2.5.5.4802
Per bartreardon: a proper workaround would be to change that line to uid=$(id -u "$currentUser" 2>/dev/null) since the error is output on stderr. As such, it's relatively innocuous as is since it won't appear in the output and $uid will be void.
> Update dialog script version message when no user logged in

- dialog/Package/pkgroot/usr/local/bin/dialog
Use the whole path for scutil to fix issues when running from a cron script, etc.
Without the whole path I get `line 2: scutil: command not found` when calling dialog from cron.
> Use whole path for scutil

- dialog.xcodeproj/project.pbxproj
- dialog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- dialog/App Processing/AppInspector.swift
- dialog/App Processing/AppVariables.swift
- dialog/App Processing/DebouncedUpdater.swift
- dialog/App Processing/FileSystemCache.swift
- dialog/App Processing/InspectConstants.swift
- dialog/Command Line/CommandLineArguments.swift
- dialog/Command Line/ProcessCLOptions.swift
- dialog/Views/Inspect/FSEventsInspector.swift
- dialog/Views/Inspect/InspectConfigurationService.swift
- dialog/Views/Inspect/InspectLayoutProtocol.swift
- dialog/Views/Inspect/InspectState.swift
- dialog/Views/Inspect/InspectValidationService.swift
- dialog/Views/Inspect/InspectView.swift
- dialog/Views/Inspect/Preset1Layout.swift
- dialog/Views/Inspect/Preset2Layout.swift
- dialog/Views/Inspect/Preset3Layout.swift
- dialog/Views/Inspect/Preset4Layout.swift
- dialog/Views/Inspect/Preset5Layout.swift
- dialog/dialogApp.swift
- Supports inspect on files, folders existence, and introspect plist configurations
- Basic plist validation types (exists, boolean, contains, range, equals)
- Includes 5 preset layouts for common enrollment progress and inspection tasks
- Uses file system events (FSEvents) to trigger UI updates
- Integrates InspectValidationService and InspectConfigurationService into Xcode build system
- Moved AppInspector startup to InspectState for better handling
- Due to build errors updated MarkdownUI from 2.3.0 to 2.4.1
Adds 17 new files and modifies 5 existing ones.
Usage: DIALOG_INSPECT_CONFIG=/path/to/inspect_config.json /usr/local/bin/dialog --inspect-mode
> Add inspect mode with service-oriented validation architecture
