swiftDialog/swiftDialog

dialog.xcodeproj/project.pbxproj, dialog/Info.plist, dialog/UI/ContentView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift
Adds `--moveable` and `--ontop` command line options to control window behaviour
=> Keep on top

dialog/Info.plist, dialog/UI/ContentView.swift, dialog/UI/DialogView.swift, dialog/UI/IconOverlayView.swift, dialog/UI/TitleView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift
Initially was supposed to be small windows only but then by writing in a scaling factor I can make big windows as well
Still not perfect. Needs special massaging of the icon overlay and button area. Should fix that up later which should provide a way for arbitrary scaling. Still learning the ropes of VStacks and HStacks.
=> Smallwindow

dialog/Info.plist, dialog/UI/ButtonView.swift, dialog/UI/ContentView.swift, dialog/UI/IconView.swift, dialog/appVaribles.swift, dialog/extras/Processing.swift
replaced all calls to exit() with the quit function
changed dialog to exit with error if an image resource can't be loaded instead of displaying a broken image.
=> Added func for quitting

dialog/Info.plist, dialog/UI/IconView.swift
Fixed a bug where dialog would exit with an error if no icon was specified.
=> Introduced a bug in the last PR 

dialog.xcodeproj/project.pbxproj, dialog/Info.plist, dialog/UI/BannerImageView.swift, dialog/UI/ButtonView.swift, dialog/UI/ContentView.swift, dialog/UI/DialogView.swift, dialog/UI/IconOverlayView.swift, dialog/UI/MessageContentView.swift, dialog/UI/TitleView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift, dialog/extras/Processing.swift
Allow for display of banner image, instead of icon
=> Banner images

dialog.xcodeproj/project.pbxproj, dialog/Info.plist
This build is deemed release candidate 1
=> Change build to RC1

dialog.xcodeproj/project.pbxproj, dialog/Info.plist
=> 1.0 release

dialog.xcodeproj/project.pbxproj, dialog/Info.plist, dialog/UI/ContentView.swift, dialog/UI/FullscreenView.swift, dialog/UI/IconView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift
=> Fullscreen

dialog.xcodeproj/project.pbxproj, dialog/appVaribles.swift, dialog/dialogApp.swift, dialog/extras/Processing.swift
Also fixes the shell exec icon that would appear on the dock when using the cli version
=> Json output

dialog.xcodeproj/project.pbxproj, dialog/UI/ContentView.swift, dialog/UI/IconOverlayView.swift, dialog/UI/IconView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift, dialog/extras/Processing.swift
Adds support for using SF Symbols as icon and overlay icon
Adds support for Do Not Disturb. Will exit with exit code 20 if DnD is on.
=> SF Symbols and Do Not Disturb

dialog.xcodeproj/project.pbxproj, dialog/Info.plist, dialog/Storyboards/BG.storyboard, dialog/UI/BackgroundView.swift, dialog/UI/ContentView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift, dialog/extras/ProcessCLOptions.swift, dialog/extras/helpText.swift
Adds support to blur the background content behind the dialog window.
=> Blur background

dialog.xcodeproj/project.pbxproj, dialog/Info.plist, dialog/UI/BackgroundView.swift, dialog/UI/ButtonView.swift, dialog/UI/ContentView.swift, dialog/UI/DialogView.swift, dialog/UI/FullscreenView.swift, dialog/UI/IconView.swift, dialog/UI/MessageContentView.swift, dialog/UI/TaskProgressView.swift, dialog/UI/TitleView.swift, dialog/UI/timerBarView.swift, dialog/appVaribles.swift, dialog/dialogApp.swift, dialog/extras/ProcessCLOptions.swift, dialog/extras/Processing.swift, dialog/extras/TrackProgress.swift, dialog/extras/helpText.swift
Add ability to read in data from a command file and update content being displayed in the dialog window.
=> Live update

dialog.xcodeproj/project.pbxproj, dialog/Info.plist, dialog/UI/CheckboxView.swift, dialog/UI/MessageContentView.swift, dialog/appVaribles.swift, dialog/extras/JSONImport.swift, dialog/extras/ProcessCLOptions.swift, dialog/extras/Processing.swift, dialog/extras/helpText.swift
added support for using checkboxes
docco here https://github.com/bartreardon/Dialog/wiki/Checkboxes
=> Checkboxes

dialog/Info.plist, dialog/UI/BackgroundView.swift, dialog/UI/FullscreenView.swift, dialog/UI/IconView.swift, dialog/UI/ImageView.swift, dialog/dialogApp.swift, dialog/extras/WindowPositioning.swift
fixes issue https://github.com/bartreardon/Dialog/issues/74
=> Multi screen resolution detection

dialog/Info.plist, dialog/UI/ButtonView.swift, dialog/extras/TrackProgress.swift
fixes issue https://github.com/bartreardon/Dialog/issues/73
=> fix `--button1text` and `--timer` hang issue

dialog.xcodeproj/project.pbxproj, dialog/Info.plist
Fixes issue https://github.com/bartreardon/Dialog/issues/80
=> Video playback bug

dialog.xcodeproj/project.pbxproj, dialog.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, dialog.xcodeproj/xcuserdata/rea094.xcuserdatad/xcschemes/xcschememanagement.plist, dialog/Info.plist, dialog/UI/FullscreenView.swift, dialog/UI/MessageContentView.swift
=> Updated MarkdownUI from 0.5.1 to 1.1.0

dialog.xcodeproj/project.pbxproj, dialog/appVaribles.swift, dialog/extras/Processing.swift
Fix issue where selected index was not being printed if the first option (index 0) was selected.
=> Selected index bug fix

dialog/Info.plist, dialog/UI/ContentView.swift, dialog/UI/DialogView.swift, dialog/UI/FullscreenView.swift, dialog/UI/MessageContentView.swift, dialog/appVaribles.swift, dialog/extras/ProcessCLOptions.swift
Adds:
- `--centreicon` `--centericon` which will display the icon in the top centre of the window
- `--title` and `--icon` can accept the keyword `none` to suppress display
=> Additional icon options

dialog/Info.plist, dialog/UI/TextEntryView.swift, dialog/appVaribles.swift, dialog/extras/ProcessCLOptions.swift
Closes https://github.com/bartreardon/swiftDialog/issues/93
=> Add prompt text to TextFields.

dialog/Info.plist, dialog/UI/DialogView.swift, dialog/UI/DropdownView.swift, dialog/UI/MessageContentView.swift, dialog/UI/TextEntryView.swift, dialog/extras/ProcessCLOptions.swift, dialog/extras/TrackProgress.swift, dialog/extras/helpText.swift
updated icon processing
added icon: size: <num> to the list of commands that can be sent
also updated help text
=> Final incon processing

dialog/UI/ContentView.swift, dialog/UI/MessageContentView.swift, dialog/appVaribles.swift, dialog/extras/ProcessCLOptions.swift
Lets you change the cmd+q quit hotkey into something else like cmd+x or any other character of choice.
also snuck in some cleanup of the markdown code.
=> Modify quit hotkey

dialog/Package/Scripts/postinstall, dialog/Package/Scripts/preinstall
This fixes pre-install failing to actually remove the old bundle at location.
=> Add  to package scripts to target install tgt

dialog.xcodeproj/project.pbxproj, dialog/App Processing/AppVariables.swift, dialog/Functions/Notifications.swift, dialog/Updatable Content/DialogUpdatableContent.swift, dialog/Views/ContentView.swift, dialog/Views/MessageContentView.swift, dialog/dialogApp.swift
=> swiftDialog 2.4.2

dialog.xcodeproj/project.pbxproj, dialog/App Processing/AppVariables.swift, dialog/App Processing/ImageProcessing.swift, dialog/Command Line/HelpText.swift, dialog/Command Line/ProcessCLOptions.swift, dialog/Functions/Preferences.swift, dialog/Functions/Strings.swift, dialog/Info.plist, dialog/Updatable Content/DialogUpdatableContent.swift, dialog/Views/ButtonView.swift, dialog/Views/ContentView.swift, dialog/Views/IconView.swift, dialog/Views/ListView.swift, dialog/dialogApp.swift
- update command file processing so all commands are parsed for built in variables
- update processing for markdown files so built in variables get processed
- fix mini mode because button3 doesn't belong there
- fix image corner radius when displayed as a list item icon
- fix error and help sheets when displayed in a login window context
- update authorisation key localisation
=> swiftDialog 2.5.2

dialog/Package/pkgroot/usr/local/bin/dialog
=> Revert "Use whole path for scutil"

dialog/Package/pkgroot/usr/local/bin/dialog
Resubmit of #512  by request of @bartreardon
=> Use whole path for scutil (resubmit)

dialog/Views/ButtonView.swift
Fixes https://github.com/swiftDialog/swiftDialog/issues/520
Please let me know if there are any changes required.
=> Fix 520: Enable button1 usage with stacked style and timer
